### ISSUE TITLE
Gmail Action/Reactions

### ISSUE THREAD

**Issue by Arthi-chaud** [AnonymusRaccoon/Aeris#45]
Gmail

- [ ] Auth

Actions
- [ ]   receive a mail (props ⇾ author, object, body, date)
- [ ]   delete mail
- [ ]   archive mail

Reactions

- [ ]   delete mail
- [ ]   archive mail
- [ ]   send mail

**Comment by AnonymusRaccoon** [comment]
Closed in favor of AniList
